title: Victor Manuel Ortiz Salazar
#logo: /assets/img/headshot_circle.png
description: B.Sc. in Physics | Junior Data Scientist | Machine Learning | Python | SQL | Predictive Analysis & Applied Data Science | Applying scientific thinking and evidence-based data analysis to drive insights and decisions
#show_downloads: true
theme: jekyll-theme-minimal
